server:
  servlet:
    context-path: /sell
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&userSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
logging:
  pattern:
    console: "%d - %msg%n"
  file: /var/log/sell.log